### ISSUE TITLE
Confused about ryzen 5950x and ryzen 7800x3d, user error?

### ISSUE THREAD

**Issue by wazerstar** [amitxv/ReservedCpuSets#2]
So I just recently sold my 5950x system to my friend and I then just discovered this tool after "MEH" :)

If i understand this CORRECT

on the 5950x we got 2 ccx, where the first ccx is the performance one/best 8 cores and the 2nd ccx 8cores as well is the more casual/releaxed one when we compare to performance and ipc.

What I did on his system was to mark the main ccx 0-15 so it would avoid running any windows tasks on it and prioritize it 100% for gaming.

I assume this is correct yeah?

Then I would use process lasso to assign chrome,firefox etc to run on the 2nd ccx.

So selecting core 0 > 15 with ReservedCpuSets
Reboot and voilá.

We now have all none important programs running on 2nd ccx 16-31 including windows tasks

and games will take favor of only running one 1st ccx 0-15 of which games I assigned to 0-15

This is the theory of how I understand this is working.

Now I tested this on my personal 7800x3d cpu where I would set core  0-11 as not getting any tasks on it from windows.

https://i.imgur.com/FLzk3ag.png

The issue I'm encountering now is that the games etc will only run on those not being selected now where on the 5950x it actually worked as it should?

I added a little video showing that its stress testing on only on the ones that was not selected, cpu-z, cinebench,games etc is behaving the exact same on my cpu.

https://streamable.com/6gpk2w

**Comment by wazerstar** [comment]
I failed to mentioned after also setting process lasso to all specific assigned cores, they would still only run on those being set by ReservedCpuSets on my **7800x3d**, tested multiple times with different core sets etc.

**Comment by amitxv** [comment]
Hi, I think you are getting mixed up with the logic here. Windows will try **not** to schedule tasks on the CPUs you select in ReservedCpuSets. In the 5950x scenario, since you reserved the first 8 cores, all tasks should be scheduled on the last 8 cores. You didn't have to set affinity for the programs you mentioned (chrome, Firefox) to run on the last 8 cores because they already are.

There are many possibilities with this program. It is up to you to decide how you use it. You could reserve the **first** CCX/CCD as you were doing so you can set an affinity for the game to exclusively run on there. The problem with this approach is that some processes are protected in which, you may not be able to configure an affinity for the game process. For this reason, another approach you could take is reserve the **second** CCX/CCD so that all tasks are scheduled on the **first** CCX/CCD so that you can manually assign unimportant background processes to the **second** CCX/CCD. As said, there are many possibilities.

The video that you sent is the correct behaviour. Tasks are being scheduled on the unreserved CPUs.

**Comment by amitxv** [comment]
> I failed to mentioned after also setting process lasso to all specific assigned cores, they would still only run on those being set by ReservedCpuSets on my **7800x3d**, tested multiple times with different core sets etc.

Do you mean allowing a process to be scheduled on all cores? If so, that is one limitation with ReservedCpuSets. I have not discovered a method to accomplish this.

**Comment by wazerstar** [comment]
> > I failed to mentioned after also setting process lasso to all specific assigned cores, they would still only run on those being set by ReservedCpuSets on my **7800x3d**, tested multiple times with different core sets etc.
> 
> Do you mean allowing a process to be scheduled on all cores? If so, that is one limitation with ReservedCpuSets. I have not discovered a method to accomplish this.

Hey I'm pretty sure I'm doing it right and understanding it correct, but there's a flaw.

as you already mentioned and understood with the 5950x I did setup, schedules are set for the last 8 cores on ccx2 where setting games up via affinity rules only work on ccx1 works brilliant!

Now on my new 7800x3d I setup your tool to only use core 6-7-8+threads for schedules.

I would now reboot and by now nothing else will run on core 0,1,2,3,4,5,6,7,8,9 as in NOTHING.

Even if i force programs to use with the default affinity in windows task manager or with tools like process lasso, they will only run on 12-13-14,15 with this [method](https://imgur.com/FLzk3ag), where on 5950x it would be allowed to it do as intended.

**Comment by amitxv** [comment]
I see, that shouldn't be happening. User-mode affinities are supposed to override this and can be scheduled on reserved CPUs.

Just to be sure, could you show a picture of the GUI and the ``ReservedCpuSets`` registry value in ``HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\kernel`` just to be sure the GUI is clear of any bugs.

**Comment by wazerstar** [comment]
> I see, that shouldn't be happening. User-mode affinities are supposed to override this and can be scheduled on reserved CPUs.
> 
> Just to be sure, could you show a picture of the GUI and the `ReservedCpuSets` registry value in `HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\kernel` just to be sure the GUI is clear of any bugs.

With blank
https://i.imgur.com/2JmTKcz.png

With selected.
https://i.imgur.com/9AmVqGX.png

**Comment by wazerstar** [comment]
> I see, that shouldn't be happening. User-mode affinities are supposed to override this and can be scheduled on reserved CPUs.
> 
> Just to be sure, could you show a picture of the GUI and the `ReservedCpuSets` registry value in `HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\kernel` just to be sure the GUI is clear of any bugs.

Also here is a video to show the proof of it.

https://streamable.com/jo7fw6

**Comment by amitxv** [comment]
Registry value seems all good. In that case, it is just a matter of experimenting with this feature. Please keep in mind that this tool is simply managing the value of a registry key. The kernel does the actual work. Nonetheless I would love to learn more about this. Can you try set the affinity to everything but the last 6 cores? Does it obey the affinity assignment or are the last 6 still exclusively being used?

**Comment by amitxv** [comment]
Process Lasso appears to report CPU utility in % rather than time-based busy utilization which may result in misleading reports as explained in here: [Task Manager’s CPU numbers are all but meaningless](https://aaron-margosis.medium.com/task-managers-cpu-numbers-are-all-but-meaningless-2d165b421e43). Please use Windows Performance Analyzer (WPRUI) from the Windows ADK to analyze per-core utilization. See the example below

![image](https://github.com/amitxv/ReservedCpuSets/assets/86924251/3b3b280e-9226-45c9-ade6-8aab1c76d6cb)

**Comment by wazerstar** [comment]
> Process Lasso appears to report CPU utility in % rather than time-based busy utilization which may result in misleading reports as explained in here: [Task Manager’s CPU numbers are all but meaningless](https://aaron-margosis.medium.com/task-managers-cpu-numbers-are-all-but-meaningless-2d165b421e43). Please use Windows Performance Analyzer (WPRUI) from the Windows ADK to analyze per-core utilization. See the example below
> 
> ![image](https://user-images.githubusercontent.com/86924251/280469652-ddc892ca-e696-4310-9cc6-6f39460c8dbc.png)

Hi I can already tell you by the fact its not about the issue of reporting wrong threads or miss information in process lasso or in windows

When running the cine benchmark I can see its running really slow compared to when its using all cores, it also only starts with 3+3 in the opening window in cinebench when I have selected those 3 cores + threads.

More over I confirmed it running a game of cs2 where I would have lag and stutters when this tweak was applied.

**Comment by amitxv** [comment]
Did you re-install Windows after the CPU swap?

**Comment by wazerstar** [comment]
> Did you re-install Windows after the CPU swap?

No I did however re-initiate amd chipset drivers etc, also did a fresh configuration of process lasso settings etc.

If there's a way to manipulate windows registry to reset it or make changes manual, ill gladly look at at guide for that?

**Comment by amitxv** [comment]
Can you re-test on a stock Windows installation? You can configure a dual-boot. It is generally always a good idea to re-install windows after major hardware swaps.

What registry changes? If you mean the ReservedCpuSets key itself, this is explained in the README.

**Comment by wazerstar** [comment]
> Can you re-test on a stock Windows installation? You can configure a dual-boot. It is generally always a good idea to re-install windows after major hardware swaps.
> 
> What registry changes? If you mean the ReservedCpuSets key itself, this is explained in the README.

Hey I did a completely new windows 11 x64 pro build 2606 23h2 installation yesterday.

Same exact thing happens.


To the registry part was more of if there was anything we could have done from the hardware swap to re detect/reassign and force changes into registry, but that does not matter now since I did a complete reformat.

If you need to get onto my PC we can arrange that via AnyDesk / RustDesk, also if we need better comms, steam,discord or any live thing you are using?

**Comment by wazerstar** [comment]
I have some VERY interesting findings, and maybe its something you can crack?

So in ReservedCpuSets I had left the last cores from 10-15 be the ones running the reserves.

The affinity was just plain default allowing all cores, and the same issue would still happen

So I thought WHAT if I only set affinity cores to 0 and up to 9, without having the program touch 10-15 Would anything happen...? Yes it did, suddenly 0-9 starting taking action and working.

So then I added just one more core, core 10 that is meant to only run the tasks, and suddenly the program is back to ONLY running on 10-15.


The only thing that we might are missing and maybe I can relate to if anything should trigger abnormal issues would be that the cpu is a X3D chip and not a normal one with lower L3 Cache, tho I'm not sure if that has anything to do with this weird scenario.

Here's a video showing it all, so there's indeed something going on.
https://streamable.com/4omkoy

**Comment by amitxv** [comment]
In that video, technically you aren't reserving cores as you have SMT on. Would you mind re-testing with SMT disabled in BIOS?

**Comment by wazerstar** [comment]
> In that video, technically you aren't reserving cores as you have SMT on. Would you mind re-testing with SMT disabled in BIOS?



> In that video, technically you aren't reserving cores as you have SMT on. Would you mind re-testing with SMT disabled in BIOS?

Sure I can go test it, but that was not an issues on the 5950x I was using all features of the cpu including SMT where reserve was set to ccx2 only and no issues was found there, ill do it right away.

**Comment by wazerstar** [comment]
> In that video, technically you aren't reserving cores as you have SMT on. Would you mind re-testing with SMT disabled in BIOS?

Here's a video without SMT, same results.

https://streamable.com/50bu9o

**Comment by amitxv** [comment]
I don't know what is going on here, affinity policies are supposed to be strict in terms of what CPUs the process is allowed to be scheduled on. For the sake of experimenting, can you set the affinity with task manager instead of process lasso?

**Comment by wazerstar** [comment]
> I don't know what is going on here, affinity policies are supposed to be strict in terms of what CPUs the process is allowed to be scheduled on. For the sake of experimenting, can you set the affinity with task manager instead of process lasso?

Sure Just did it.

Tested with and without SMT enabled, same thing occurs only using task manager to set affinity.


One other thing I just now noted was that Process Lasso Pro can list and detect cpu sets as well.

when I sorted for cpu sets this was showing only using those cores when RCS has been set, and the cpu sets from those apps are removed again when RCS is reverting back to default windows settings, after a reboot.

I just found it odd that it would only be those and nothing anything else system wise in anyways, perhaps they are not visible for process lasso, I don't know,

Video of it.

https://streamable.com/vq4a28

**Comment by amitxv** [comment]
It seems to be finicky when setting the process affinity to both reserved and unreserved cores.

![a](https://github.com/amitxv/ReservedCpuSets/assets/86924251/227ca23c-b8b6-4201-a35c-a00b4f0e1c20)
![b](https://github.com/amitxv/ReservedCpuSets/assets/86924251/72e36a51-8819-4372-adb5-12870f119519)
![c](https://github.com/amitxv/ReservedCpuSets/assets/86924251/16b0a4ca-32ec-495a-b0d0-13bac01207f3)
![d](https://github.com/amitxv/ReservedCpuSets/assets/86924251/6b67d234-775c-4b20-b308-3cd25dda1844)
![e](https://github.com/amitxv/ReservedCpuSets/assets/86924251/63d70c8c-110d-413a-9cae-9e0c766ecc06)
![f](https://github.com/amitxv/ReservedCpuSets/assets/86924251/197dee00-40c1-4c3e-8ee9-84bfd835faa5)

**Comment by wazerstar** [comment]
Alright so its not me that is crazy, would you think there's any workaround of possible fixes for this?

if not I guess this tweak really only benefits multiple ccds

**Comment by amitxv** [comment]
It doesn't only benefit multiple CCX/CCDs. Simply don't set process affinity to unreserved and reserved CPUs. Stick to either or. There are still other [use-cases](https://github.com/amitxv/PC-Tuning/blob/main/docs/post-install.md#use-cases).

**Comment by amitxv** [comment]
Does this answer your original question in that case? The process affinity was set to unreserved and reserved CPUs in [this reply](https://github.com/amitxv/ReservedCpuSets/issues/2#issuecomment-1790368781) which we now know is the cause for this behaviour.

**Comment by wazerstar** [comment]
> Does this answer your original question in that case? The process affinity was set to unreserved and reserved CPUs in [this reply](https://github.com/amitxv/ReservedCpuSets/issues/2#issuecomment-1790368781) which we now know is the cause for this behaviour. @wazerstar

Indeed it, thanks.

I'm ordering at 7950x3d and selling/returning my 7800x3d, my mind tells me to get it since I want to use this tweak :)

**Comment by amitxv** [comment]
I like the single CCX design of the 7800x3d. You don't need multiple CCXs/CCDs to reserve CPUs. I'm not sure what you have in mind that you will do differently with a 7950x3d.

**Comment by wazerstar** [comment]
> I like the single CCX design of the 7800x3d. You don't need multiple CCXs/CCDs to reserve CPUs. I'm not sure what you have in mind that you will do differently with a 7950x3d.

I want obs,all my streaming services and all other drivers running on the 2nd one.
