### ISSUE TITLE
cpu intensive apps not utilizing all threads

### ISSUE THREAD

**Issue by mekakii** [amitxv/ReservedCpuSets#5]
I have a 5900x and I reserved the second ccd for games but even apps like winrar, cinebench and other apps that can utilize more than 12 threads doesn't seem to be using all 24 threads on my CPU even though I have set the application to all cores with process lasso. 

is this a normal thing or am I doing something wrong?

**Comment by amitxv** [comment]
I'm not sure what you mean. Generally speaking, light apps that are not specifically assigned to reserved cores will not run on them. Heavy apps will use all cores regardless. Theoretically Cinebench multi-core benchmark should be heavy enough to utilize all cores but I don't know for certain. Regarding forcing an app to use all cores including reserved cores, I'm not aware of a method to achieve this. Furthermore, unexpected results occur when setting an affinity to both unreserved and reserved cores as stated in the README

**Comment by mekakii** [comment]
When I did a cinebench test before it only used the reserved cores I have set up which is my second ccd in my 5900x and not the entire 12 cores.

**Comment by amitxv** [comment]
It's likely not heavy enough then. As mentioned before, it is not recommended to set affinity to both unreserved and reserved CPUs.

**Comment by mekakii** [comment]
alright alright
